#include "../Inc/GPIO_config.h"

void GPIO_config()
{
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOC);                    // все SDIO контакты кроме SDIO_CMD
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOD);

    LL_GPIO_SetPinSpeed(GPIOC,LL_GPIO_PIN_8,LL_GPIO_SPEED_FREQ_HIGH);       // SDIO_D0
    LL_GPIO_SetPinSpeed(GPIOC,LL_GPIO_PIN_9,LL_GPIO_SPEED_FREQ_HIGH);       // SDIO_D1
    LL_GPIO_SetPinSpeed(GPIOC,LL_GPIO_PIN_10,LL_GPIO_SPEED_FREQ_HIGH);      // SDIO_D2
    LL_GPIO_SetPinSpeed(GPIOC,LL_GPIO_PIN_11,LL_GPIO_SPEED_FREQ_HIGH);      // SDIO_D3
    LL_GPIO_SetPinSpeed(GPIOC,LL_GPIO_PIN_12,LL_GPIO_SPEED_FREQ_HIGH);      // SDIO_Ck

    LL_GPIO_SetPinSpeed(GPIOD,LL_GPIO_PIN_2,LL_GPIO_SPEED_FREQ_HIGH);       // SDIO_CMD

    LL_GPIO_SetPinOutputType(GPIOC,LL_GPIO_PIN_8,LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinOutputType(GPIOC,LL_GPIO_PIN_9,LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinOutputType(GPIOC,LL_GPIO_PIN_10,LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinOutputType(GPIOC,LL_GPIO_PIN_11,LL_GPIO_OUTPUT_PUSHPULL);
    //LL_GPIO_SetPinOutputType(GPIOC,LL_GPIO_PIN_12,LL_GPIO_OUTPUT_PUSHPULL);

    LL_GPIO_SetPinOutputType(GPIOD,LL_GPIO_PIN_2,LL_GPIO_OUTPUT_PUSHPULL);

    LL_GPIO_SetPinPull(GPIOC,LL_GPIO_PIN_8,LL_GPIO_PULL_UP);
    LL_GPIO_SetPinPull(GPIOC,LL_GPIO_PIN_9,LL_GPIO_PULL_UP);
    LL_GPIO_SetPinPull(GPIOC,LL_GPIO_PIN_10,LL_GPIO_PULL_UP);
    LL_GPIO_SetPinPull(GPIOC,LL_GPIO_PIN_11,LL_GPIO_PULL_UP);
    //LL_GPIO_SetPinPull(GPIOC,LL_GPIO_PIN_12,LL_GPIO_PULL_UP);
    LL_GPIO_SetPinPull(GPIOD,LL_GPIO_PIN_2,LL_GPIO_PULL_UP);

    LL_GPIO_SetPinMode(GPIOC,LL_GPIO_PIN_8,LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinMode(GPIOC,LL_GPIO_PIN_9,LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinMode(GPIOC,LL_GPIO_PIN_10,LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinMode(GPIOC,LL_GPIO_PIN_11,LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetPinMode(GPIOC,LL_GPIO_PIN_12,LL_GPIO_MODE_ALTERNATE);

    LL_GPIO_SetPinMode(GPIOD,LL_GPIO_PIN_2,LL_GPIO_MODE_ALTERNATE);

    LL_GPIO_SetAFPin_8_15(GPIOC,LL_GPIO_PIN_8,LL_GPIO_AF_12);
    LL_GPIO_SetAFPin_8_15(GPIOC,LL_GPIO_PIN_9,LL_GPIO_AF_12);
    LL_GPIO_SetAFPin_8_15(GPIOC,LL_GPIO_PIN_10,LL_GPIO_AF_12);
    LL_GPIO_SetAFPin_8_15(GPIOC,LL_GPIO_PIN_11,LL_GPIO_AF_12);
    LL_GPIO_SetAFPin_8_15(GPIOC,LL_GPIO_PIN_12,LL_GPIO_AF_12);

    LL_GPIO_SetAFPin_0_7(GPIOD,LL_GPIO_PIN_2,LL_GPIO_AF_12);

    if (!LL_AHB1_GRP1_IsEnabledClock(LL_AHB1_GRP1_PERIPH_GPIOA))
        LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

    LL_GPIO_SetPinMode(GPIOA,LL_GPIO_PIN_9,LL_GPIO_MODE_ALTERNATE);     // USART1 Tx
    LL_GPIO_SetPinMode(GPIOA,LL_GPIO_PIN_10,LL_GPIO_MODE_ALTERNATE);    // USART1 Rx

    LL_GPIO_SetAFPin_8_15(GPIOA,LL_GPIO_PIN_9,LL_GPIO_AF_7);
    LL_GPIO_SetAFPin_8_15(GPIOA,LL_GPIO_PIN_10,LL_GPIO_AF_7);
    
}